import { v4 as uuid } from 'uuid';
import { formatDate } from '../utils/authUtils';
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: 1,
    firstName: 'Amar',
    lastName: 'Narute',
    username: 'amarnarute',
    password: 'amarnarute123',
    following: [],
    followers: [
      {
        _id: 2,
        firstName: 'Adarsh',
        lastName: 'Balika',
        username: 'adarshbalika',
        password: 'adarshBalika123',
        createdAt: formatDate(),
        updatedAt: formatDate(),
      },
    ],
    stories: [
      {
        username: 'adarshbalika',
        images: [
          'https://res.cloudinary.com/dq81bdilo/image/upload/v1652903654/nattu-adnan-Ai2TRdvI6gM-unsplash_yzille.webp',
          'https://res.cloudinary.com/dq81bdilo/image/upload/v1652903655/maxwell-nelson-1r2CG6EQ4-Y-unsplash_bg8haz.webp',
        ],
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 3,
    firstName: 'Abhi',
    lastName: 'Shaikh',
    username: 'abhishaikh',
    password: 'abhishaikh123',
    followers: [],
    following: [],
    stories: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 4,
    firstName: 'Vivek',
    lastName: 'Bindra',
    username: 'vivekbindra',
    password: 'vivekbindra123',
    followers: [],
    following: [],
    stories: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 2,
    firstName: 'Adarsh',
    lastName: 'Balika',
    username: 'adarshbalika',
    password: 'adarshBalika123',
    displayPicture:
      'https://res.cloudinary.com/dq81bdilo/image/upload/v1652903653/hello-hi_cx6nyi.webp',
    followers: [],
    following: [
      {
        _id: 1,
        firstName: 'Amar',
        lastName: 'Narute',
        username: 'amarnarute',
        password: 'amarnarute123',
        stories: [
          {
            username: 'amarnarute',
            images: [
              'https://res.cloudinary.com/dq81bdilo/image/upload/v1652903654/nattu-adnan-Ai2TRdvI6gM-unsplash_yzille.webp',
              'https://res.cloudinary.com/dq81bdilo/image/upload/v1652903655/maxwell-nelson-1r2CG6EQ4-Y-unsplash_bg8haz.webp',
            ],
          },
        ],
        createdAt: formatDate(),
        updatedAt: formatDate(),
      },
    ],
    stories: [
      {
        username: 'adarshbalika',
        images: [
          'https://res.cloudinary.com/dq81bdilo/image/upload/v1652903653/terrylknox-ZSCB-1GovZ8-unsplash_vgzz96.webp',
          'https://res.cloudinary.com/dq81bdilo/image/upload/v1652903652/photo-1529524987368-af489318987c_m9obqe.webp',
        ],
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 5,
    firstName: 'Bad',
    lastName: 'Balak',
    username: 'badbalak',
    password: 'badbalak123',
    followers: [],
    following: [],
    stories: [
      {
        username: 'badbalak',
        images: [
          'https://res.cloudinary.com/dq81bdilo/image/upload/v1652903653/hello-hi_cx6nyi.webp',
          'https://res.cloudinary.com/dq81bdilo/image/upload/v1652903653/ian-kirkland-v2kwQjH4IDs-unsplash_inusmn.webp',
        ],
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 6,
    firstName: 'Rohit',
    lastName: 'Mishra',
    username: 'rohitmishra',
    password: 'rohitmishra123',
    followers: [],
    following: [],
    stories: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 7,
    firstName: 'Elon',
    lastName: 'Musk',
    username: 'elonmusk',
    password: 'elonmusk123',
    bio: 'Badass.',
    followers: [],
    following: [],
    stories: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 8,
    firstName: 'Abhinav',
    lastName: 'Bindra',
    username: 'abhinavbindra',
    password: 'abhinavbindra123',
    followers: [],
    following: [],
    stories: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 9,
    firstName: 'Tiger',
    lastName: 'Shroff',
    username: 'tigershroff',
    password: 'tigershroff123',
    followers: [],
    following: [],
    stories: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 10,
    firstName: 'Hrithik',
    lastName: 'Roshan',
    username: 'hrithikroshan',
    password: 'hrithikroshan123',
    followers: [],
    following: [],
    stories: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
