import { v4 as uuid } from 'uuid';
import { formatDate } from '../utils/authUtils';
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: 1,
    firstName: 'Amar',
    lastName: 'Narute',
    username: 'amarnarute',
    password: 'amarnarute123',
    following: [],
    followers: [
      {
        _id: 2,
        firstName: 'Adarsh',
        lastName: 'Balika',
        username: 'adarshbalika',
        password: 'adarshBalika123',
        createdAt: formatDate(),
        updatedAt: formatDate(),
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 3,
    firstName: 'Abhi',
    lastName: 'Shaikh',
    username: 'abhishaikh',
    password: 'abhishaikh123',
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 4,
    firstName: 'Vivek',
    lastName: 'Bindra',
    username: 'vivekbindra',
    password: 'vivekbindra123',
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 2,
    firstName: 'Adarsh',
    lastName: 'Balika',
    username: 'adarshbalika',
    password: 'adarshBalika123',
    followers: [],
    following: [
      {
        _id: 1,
        firstName: 'Amar',
        lastName: 'Narute',
        username: 'amarnarute',
        password: 'amarnarute123',
        createdAt: formatDate(),
        updatedAt: formatDate(),
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 5,
    firstName: 'Bad',
    lastName: 'Balak',
    username: 'badbalak',
    password: 'badbalak123',
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 6,
    firstName: 'Rohit',
    lastName: 'Mishra',
    username: 'rohitmishra',
    password: 'rohitmishra123',
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 7,
    firstName: 'Elon',
    lastName: 'Musk',
    username: 'elonmusk',
    password: 'elonmusk123',
    bio: 'Badass.',
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 8,
    firstName: 'Abhinav',
    lastName: 'Bindra',
    username: 'abhinavbindra',
    password: 'abhinavbindra123',
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 9,
    firstName: 'Tiger',
    lastName: 'Shroff',
    username: 'tigershroff',
    password: 'tigershroff123',
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: 10,
    firstName: 'Hrithik',
    lastName: 'Roshan',
    username: 'hrithikroshan',
    password: 'hrithikroshan123',
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
